// ============================================================
// 🔌 OPTION: Phase 4 Extensions (Save, Finalize, Export)
// ============================================================
// Writing custom logic here extends how chunks are written out
// and allows you to add post-processing after completion.
//
// Usage:
//   - If left as `null`, the default engine logic is used as-is.
//   - If a function is provided, its logic is executed before, after, or instead of the default.
//
// Examples of features that can be added (see options_docs/phase4):
//   - Export as a Zip archive
//   - Export in JSON / YAML formats
//   - Automatically execute another command after export (e.g., git add)
//   - Automatically prepend/append headers and footers to each chunk
// ============================================================

// ──────────────────────────────────────────────────────────
// Chunk Content Transformation Hook
// ──────────────────────────────────────────────────────────

// Called right before writing each chunk to a file.
// Receives the content and returns the processed string.
// If left as `null`, it performs the default behavior (writes as-is).
//
// Example: Adding a common footer to each file
// exports.transformChunk = (content, filename, config) => {
//     return content + '\n\n---\n*Generated by SPLIST*\n';
// };
exports.transformChunk = null;


// ──────────────────────────────────────────────────────────
// Post-Completion Hook
// ──────────────────────────────────────────────────────────

// A post-processing hook called after finishProcess.
// If left as `null`, it performs the default behavior (does nothing).
//
// Example: Automatically run git add on the output folder
// exports.afterFinish = (outDir, config) => {
//     const { execSync } = require('child_process');
//     execSync(`git add "${outDir}"`, { stdio: 'inherit' });
// };
exports.afterFinish = null;
